version: "3.7"
services:
  api:
    restart: always
    labels:
      infra.type: api
    build:
      context: ./
      dockerfile: api/Dockerfile
  frontend:
    restart: always
    labels:
      infra.type: frontend
    environment:
      API_PROXY_URL: http://api:3000
    depends_on:
      - api
    build:
      context: ./
      dockerfile: frontend/Dockerfile
